WebApplication1/Models/ErrorViewModel.cs
using System;

namespace WebApplication1.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebApplication1/Models/SlotEntry.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication1.Models
{
    public class SlotEntry
    {
        public string Id { get; set; }

        public string GoldNumber { get; set; }

        public string ShubhlakshamiNumber { get; set; }

        public string RajashriNumber { get; set; }

        public string Star { get; set; }
        public DateTime DateTime { get; set; }
        public string Slot { get; set; }
    }
}

WebApplication1/Models/SlotEntryViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication1.Models
{
    public class SlotEntryViewModel
    {
        public DateTime Date { get; set; }
        public string[] Ga { get; set; }
        public string[] Ra { get; set; }
        public string[] Su { get; set; }
        public string[] St { get; set; }
    }
}

WebApplication1/Areas/Admin/Controllers/SlotEntriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplication1.Data;
using WebApplication1.Models;

namespace WebApplication1.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class SlotEntriesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public SlotEntriesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Admin/SlotEntries
        public async Task<IActionResult> Index(DateTime? date)
        {
            date=date??DateTime.Now.Date;
            return View(await _context.SlotEntry.Where(i=>i.DateTime.Date==date.Value.Date).ToListAsync());
        }

        // GET: Admin/SlotEntries/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var slotEntry = await _context.SlotEntry
                .FirstOrDefaultAsync(m => m.Id == id);
            if (slotEntry == null)
            {
                return NotFound();
            }

            return View(slotEntry);
        }

        // GET: Admin/SlotEntries/Create
        public IActionResult Create()
        {
            return View();
        }


        public IActionResult createbulk()
        {
            return View();
        }

        [HttpPost]
        public IActionResult createbulk(SlotEntryViewModel model)
        {
            var slots = TimeZoneInfo.ConvertTime( new DateTime(model.Date.Year,model.Date.Month,model.Date.Day,10,0,0),TimeZoneInfo.FindSystemTimeZoneById("India Standard Time"));
            List<SlotEntry> entries = new List<SlotEntry>();
            for(int i=0;i<model.Ga.Length;i++){
                var entry = new SlotEntry();
               
                entry.DateTime = slots.AddMinutes(i*15);
                entry.Id = entry.DateTime.Ticks.ToString();
                entry.GoldNumber = model.Ga[i];
                entry.RajashriNumber = model.Ra[i];
                entry.ShubhlakshamiNumber = model.Su[i];
                entry.Star = model.St[i];
                entries.Add(entry);
                
            }
            _context.SlotEntry.AddRange(entries);
            _context.SaveChanges();
            return View(model);
        }
        // POST: Admin/SlotEntries/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,GoldNumber,ShubhlakshamiNumber,RajashriNumber,Star,DateTime,Slot")] SlotEntry slotEntry)
        {
            if (ModelState.IsValid)
            {
                _context.Add(slotEntry);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(slotEntry);
        }

        // GET: Admin/SlotEntries/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var slotEntry = await _context.SlotEntry.FindAsync(id);
            if (slotEntry == null)
            {
                return NotFound();
            }
            return View(slotEntry);
        }

        // POST: Admin/SlotEntries/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Id,GoldNumber,ShubhlakshamiNumber,RajashriNumber,Star,DateTime,Slot")] SlotEntry slotEntry)
        {
            if (id != slotEntry.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(slotEntry);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SlotEntryExists(slotEntry.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(slotEntry);
        }

        // GET: Admin/SlotEntries/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var slotEntry = await _context.SlotEntry
                .FirstOrDefaultAsync(m => m.Id == id);
            if (slotEntry == null)
            {
                return NotFound();
            }

            return View(slotEntry);
        }

        // POST: Admin/SlotEntries/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var slotEntry = await _context.SlotEntry.FindAsync(id);
            _context.SlotEntry.Remove(slotEntry);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SlotEntryExists(string id)
        {
            return _context.SlotEntry.Any(e => e.Id == id);
        }
    }
}

WebApplication1/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WebApplication1.Data;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class HomeController : Controller
    {
        private ApplicationDbContext _context;
        public HomeController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var result = _context.SlotEntry.ToList();
            return View(result);
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebApplication1/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication1</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">WebApplication1</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - WebApplication1</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

WebApplication1/Areas/Admin/Views/SlotEntries/Create.cshtml
@model WebApplication1.Models.SlotEntry

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>SlotEntry</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" asp-area="admin">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="GoldNumber" class="control-label"></label>
                <input asp-for="GoldNumber" class="form-control" />
                <span asp-validation-for="GoldNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ShubhlakshamiNumber" class="control-label"></label>
                <input asp-for="ShubhlakshamiNumber" class="form-control" />
                <span asp-validation-for="ShubhlakshamiNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RajashriNumber" class="control-label"></label>
                <input asp-for="RajashriNumber" class="form-control" />
                <span asp-validation-for="RajashriNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Star" class="control-label"></label>
                <input asp-for="Star" class="form-control" />
                <span asp-validation-for="Star" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateTime" class="control-label"></label>
                <input asp-for="DateTime" class="form-control" />
                <span asp-validation-for="DateTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Slot" class="control-label"></label>
                <input asp-for="Slot" class="form-control" />
                <span asp-validation-for="Slot" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApplication1/Areas/Admin/Views/SlotEntries/Delete.cshtml
@model WebApplication1.Models.SlotEntry

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>SlotEntry</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.GoldNumber)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.GoldNumber)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ShubhlakshamiNumber)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ShubhlakshamiNumber)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.RajashriNumber)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.RajashriNumber)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Star)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Star)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DateTime)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DateTime)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Slot)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Slot)
        </dd>
    </dl>
    
    <form asp-action="Delete" asp-area="admin">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

WebApplication1/Areas/Admin/Views/SlotEntries/Details.cshtml
@model WebApplication1.Models.SlotEntry

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>SlotEntry</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.GoldNumber)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.GoldNumber)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ShubhlakshamiNumber)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ShubhlakshamiNumber)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.RajashriNumber)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.RajashriNumber)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Star)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Star)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DateTime)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DateTime)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Slot)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Slot)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-area="admin" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index" asp-area="admin" asp-controller="SlotEntries">Back to List</a>
</div>

WebApplication1/Areas/Admin/Views/SlotEntries/Edit.cshtml
@model WebApplication1.Models.SlotEntry

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>SlotEntry</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" asp-area="admin">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="GoldNumber" class="control-label"></label>
                <input asp-for="GoldNumber" class="form-control" />
                <span asp-validation-for="GoldNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ShubhlakshamiNumber" class="control-label"></label>
                <input asp-for="ShubhlakshamiNumber" class="form-control" />
                <span asp-validation-for="ShubhlakshamiNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RajashriNumber" class="control-label"></label>
                <input asp-for="RajashriNumber" class="form-control" />
                <span asp-validation-for="RajashriNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Star" class="control-label"></label>
                <input asp-for="Star" class="form-control" />
                <span asp-validation-for="Star" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateTime" class="control-label"></label>
                <input asp-for="DateTime" class="form-control" />
                <span asp-validation-for="DateTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Slot" class="control-label"></label>
                <input asp-for="Slot" class="form-control" />
                <span asp-validation-for="Slot" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApplication1/Areas/Admin/Views/SlotEntries/Index.cshtml
@model IEnumerable<WebApplication1.Models.SlotEntry>

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>



<p>
    <a asp-action="Create" asp-area="admin" asp-controller="slotentries">Create New</a>
</p>
<form>
    <input type="date" name="date"/ ><button>Go</button>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.GoldNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ShubhlakshamiNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RajashriNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Star)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateTime)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Slot)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.OrderBy(i=>i.Id)) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.GoldNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ShubhlakshamiNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RajashriNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Star)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateTime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Slot)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

WebApplication1/Areas/Admin/Views/SlotEntries/createBulk.cshtml
@{
    ViewData["Title"] = "createBulk";
    int hour = 10;
    int minute = 0;
    string am = "am";
}

<h2>createBulk</h2>


<form asp-action="createbulk">
    <div class="row">
        <div class="col-md-4">For Date</div>
        <div class="col-md-8">
            <input type="date" name="date" class="form-control"/>
        </div>
    </div>
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Time</th>
                <th>Golden-A</th>
                <th>Shubhlakshami-A</th>
                <th>Rajshri</th>
                <th>Star</th>
            </tr>
        </thead>

        @for (int i = 0; i < (12 * 4) -2; i++)
        {
            <tr>
                <td>@hour : @minute.ToString("00") @am</td>
                <td><input name="Ga" type="text" class="form-control"/></td>

                <td><input name="Su" type="text" class="form-control"/></td>
                <td><input name="Ra" type="text" class="form-control"/></td>
                <td><input name="st" type="text" class="form-control"/></td>
                @if (minute == 45)
                {

                    hour++;
                    if (hour == 13)
                    { hour = 1;
                        am = "pm";
                    }
                    minute = 0;
                }
                else
                {

                    minute += 15;
                }
            </tr>
        }

          
        </table>
    <button class="btn btn-default">Save</button>
</form>

WebApplication1/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

WebApplication1/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

WebApplication1/Views/Home/Index.cshtml
@model IEnumerable<WebApplication1.Models.SlotEntry>
@{
    ViewData["Title"] = "Home Page";
}

<div class="row">
    <div class="col-md-12">

        <table class="table table-bordered table-responsive tt">
            <tr>
                <th>
                    Time
                </th>
                <th>
                    Golden
                </th>
                <th>
                    Shubhalakshmi
                </th>
                <th>
                    Rajshri
                </th>
                <th>Goa Lucky</th>
            </tr>
            @foreach (var item in Model)
            {
                <tr>
                    <th class="red_table">
                        @item.DateTime.ToString("hh:mm tt")
                    </th>
                    <th class="blue_table">
                        @item.GoldNumber
                    </th>
                    <th class="green_table">
                        @item.ShubhlakshamiNumber
                    </th>
                    <th class="cyan_table">
                        @item.RajashriNumber
                    </th>
                    <th class="gold_table">@item.Star</th>
                </tr>
            }
        </table>
    </div>
</div>